// all of the action types
// we will use these so spelling errors don't break our actions

// session consts
export const CREATE_SESSION = "CREATE_SESSION";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_ERROR = "CREATE_SESSIION_ERROR";
export const UPDATE_SESSION = "UPDATE_SESSION";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_ERROR = "UPDATE_SESSIION_ERROR";
export const DELETE_SESSION = "DELETE_SESSION";
export const DELETE_SESSION_SUCCESS = "DELETE_SESSION_SUCCESS";
export const DELETE_SESSION_ERROR = "DELETE_SESSION_ERROR";
export const GET_SESSIONS= "GET_SESSIONS";
export const GET_SESSIONS_SUCCESS = "GET_SESSIONS_SUCCESS";
export const GET_SESSIONS_ERROR = "GET_SESSIONS_ERROR";
export const GET_SESSION_BY_DATE = "GET_SESSION_BY_DATE";
export const GET_SESSION_BY_DATE_SUCCESS = "GET_SESSION_BY_DATE_SUCCESS";
export const GET_SESSION_BY_DATE_ERROR = "GET_SESSION_BY_DATE_ERROR";

// authentication consts
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// sign up consts
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// alert consts
export const LOGIN_ALERT_SUCCESS = 'LOGIN_ALERT_SUCCESS';
export const LOGIN_ALERT_ERROR = 'LOGIN_ALERT_ERROR';
export const LOGIN_ALERT_CLEAR = 'LOGIN_ALERT_CLEAR';
export const SIGNUP_ALERT_SUCCESS = 'SIGNUP_ALERT_SUCCESS';
export const SIGNUP_ALERT_ERROR = 'SIGNUP_ALERT_ERROR';
export const SIGNUP_ALERT_CLEAR = 'SIGNUP_ALERT_CLEAR';
export const PLAN_ALERT_SUCCESS = 'PLAN_ALERT_SUCCESS';
export const PLAN_ALERT_ERROR = 'PLAN_ALERT_ERROR';
export const PLAN_ALERT_CLEAR = 'PLAN_ALERT_CLEAR';
export const UPDATE_ALERT_SUCCESS = 'UPDATE_ALERT_SUCCESS';
export const UPDATE_ALERT_ERROR = 'UPDATE_ALERT_ERROR';
export const UPDATE_ALERT_CLEAR = 'UPDATE_ALERT_CLEAR';
export const DELETE_ALERT_SUCCESS = 'DELETE_ALERT_SUCCESS';
export const DELETE_ALERT_ERROR = 'DELETE_ALERT_ERROR';
export const DELETE_ALERT_CLEAR = 'DELETE_ALERT_CLEAR';



